### ISSUE TITLE
Add flag for disabling default features when building contracts

### ISSUE THREAD

**Issue by 0xekez** [CosmWasm/rust-optimizer#107]
multichain projects may want to enable/disable contract features for different chains they deploy on.

for example, as cw20s are [phased out](https://hackmd.io/@reecepbcups/cw20-to-tokenfactory) in favor of TokenFactory some deployments will need cw20 support, and some will use only native tokens. for example, Juno makes extensive use of the cw20 standard, but Osmosis deals entirely in native tokens.

in DAO DAO we're moving cw20 support [behind a cargo feature flag](https://github.com/DA0-DA0/dao-contracts/pull/571) that is enabled by default. it would be great to be able to enable / disable that as an argument to `workspace-optimizer` to make reproducible builds easier.

**Comment by webmaster128** [comment]
Yeah. This is already discussed in https://github.com/CosmWasm/rust-optimizer/issues/80. TLDR: The moment we allow that, code verification gets significantly mre complex as more inputs need to be maintained.

**Comment by 0xekez** [comment]
ah, i missed that. thanks for pointing to the other issue @webmaster128! i'll move further investigation there.
