### ISSUE TITLE
Optimize workspace-optimizer compile time

### ISSUE THREAD

**Issue by doquockhanhan** [CosmWasm/rust-optimizer#123]
Hi team,
I am facing an issue where a workspace contract took too long to compile on Kubernetes comparing to when I run it local. I don't know what is the root cause of this issue, but I think one way to work around this is to have a way to define the contract that needs to compile in the workspace, so that the image only compile that contract rather than the hold contracts in workspace.

**Comment by webmaster128** [comment]
Which version are you using?

Are you compiling on the native CPU type? I.e. use cosmwasm/workspace-optimizer for x86_64 and cosmwasm/workspace-optimizer-arm64 for ARM machines?

**Comment by webmaster128** [comment]
Any updates here?

**Comment by doquockhanhan** [comment]
> Which version are you using?
> 
> Are you compiling on the native CPU type? I.e. use cosmwasm/workspace-optimizer for x86_64 and cosmwasm/workspace-optimizer-arm64 for ARM machines?

oops sorry I totally forgot after posting the issue. Yes I'm using the correct image for my OS. And it happens for pretty much all the versions.

**Comment by webmaster128** [comment]
What does "took too long" mean? At which point does it break?

Did you try the latest 0.12.13? This enables Cargo's sparse protocol which makes loading the crates.io index significantly faster. It might explain the difference between local an remote because locally you can use some cache.

How large is the codebase? How long does a local recompile take?

**Comment by doquockhanhan** [comment]
I also use a volume to cache the crates.io on remote but that makes no different. After inspecting the log I found out that it is the compile step that takes up time but not the downloading crates step. 

Normally in local it takes ~10mins to compile a cw-nfts or cw-plus workspace contract but on remote it usually takes >30mins to compile the same source code. And it often gets stuck at the compile step, like it is compiling a few packages and then it stopped for like a minute or so and then it continue to compile the next one, and that repeats for several times until the compile process complete.

**Comment by webmaster128** [comment]
I know nothing about Kubernetes and stuff but it sounds like you have some restricted resources there.

How is your memory usage? Is the process swapping to disk? Is it compiling on multiple cores?

**Comment by webmaster128** [comment]
Maybe it is also a matter of expectations. Are you building the Wasm file on every commit? I think best practice is to only compile them for releases.

In some other project we use [this script](https://github.com/noislabs/nois-contracts/blob/v0.13.5/devtools/build_integration_wasm.sh#L12-L30) to build local Wasm files. This is much faster than going through workspace-optimizer but not suiteable for reproducible builds and verification.

**Comment by doquockhanhan** [comment]
Yup got it. Cheers.
