### ISSUE TITLE
Find new name for this repo

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/rust-optimizer#14]
In https://github.com/CosmWasm/cosmwasm-examples/issues/60 a discussion about this repo's name and the docker image name evolved. Let's move this discussion here.

Right now, we have
- Repo: CosmWasm/cosmwasm-opt
- Docker: confio/cosmwasm-opt

I'd like to implement the following changes for the new name
1. Use the docker organization [cosmwasm](https://hub.docker.com/r/cosmwasm)
2. Add the term "rust" to prepare for a similar project for assemblyscript
3. (bonus) Keep the term "optimize" somehow, as this remains the goal here and differentiates this from simply running cargo

Suggestion 1 (by Ethan):

- Repo: CosmWasm/rust-builder
- Docker: cosmwasm/rust-builder

Alternative:

- Repo: CosmWasm/rust-optimizer
- Docker: cosmwasm/rust-optimizer

Other ideas? Other aspects to consider?

**Comment by ethanfrey** [comment]
> CosmWasm/rust-optimizer

I like this better than my suggestion.
And yes, docker and repo should be in the same org

**Comment by ethanfrey** [comment]
Renaming this is easy, but then requires updating a lot of references in docs

**Comment by webmaster128** [comment]
```
Repo: CosmWasm/rust-optimizer
Docker: cosmwasm/rust-optimizer
```

it is. Since the only thing that changes between `confio/cosmwasm-opt:0.7.3` and `cosmwasm/rust-optimizer:0.8.0` is the Rust version 1.41.1 -> 1.43.1, we can change it step-by-step.
