### ISSUE TITLE
Try using a cross-workspace compile cache

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/rust-optimizer#27]
After https://github.com/CosmWasm/rust-optimizer/pull/26 it would be nice "to share built dependencies across different workspaces". This can be done using sccache: https://doc.rust-lang.org/cargo/guide/build-cache.html#shared-cache

I never tried this. Would be good to have a look, and see how much we can win by doing that.

**Comment by maurolacy** [comment]
Nice. I'll take a look.

**Comment by maurolacy** [comment]
We would need to put the cache on a cloud storage, as (AFAIK) the local disks / volumes in the ci build are not persistent.

There are multiple cloud storage options. See [sccache-storage-options](https://github.com/mozilla/sccache#storage-options).

@webmaster128, what do you think / suggest?

**Comment by webmaster128** [comment]
Let's just use local caching. This already saves a lot of time when compiling the dependencies of multiple contracts that have their own target folders.
