### ISSUE TITLE
Use pre-compiled sccache

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/rust-optimizer#33]
Compiling sccache takes a lot of time when building the images. We could instead download the binaries from GitHub:
https://github.com/mozilla/sccache/releases/tag/v0.2.15

**Comment by maurolacy** [comment]
Why not caching the `sccache` binaries? 🤡

**Comment by webmaster128** [comment]
Since we start with a [430MB image](https://hub.docker.com/layers/rust/library/rust/1.51.0/images/sha256-18b8317ec5971a05b608c53ba21b4d6965ff459aa803e8e4181648f6d9f22af7?context=explore), add very little and and up with a 1.8GB rust-optimizer image, it seems like we ship all intermediate build artifacts of sccache to our users.

**Comment by maurolacy** [comment]
Good point. Removing the sccache artifacts at the end of the builds, or putting them into external storage will solve this.

**Comment by maurolacy** [comment]
> We could instead download the binaries from GitHub:
> https://github.com/mozilla/sccache/releases/tag/v0.2.15

Those binaries are for the sccache client, that lacks the functionality we're using. We either:

- Stick to building the sccache binary; maybe for debug, to sped up building.
- Download the binaries from another place, if we can find a suitable one.
- Move to using client version of sccache.

An alternative to building every time is to build our own image (something like `rust-optimizer-base`), tag it and publish it, and then use it as a basis to building `rust-optimizer`. That is, moving stuff from the dockerfile to another dockerfile, for the base image.

I'm exploring alternatives. Will comment back on what I find.

**Comment by webmaster128** [comment]
> Those binaries are for the sccache client, that lacks the functionality we're using.

Why do you think so? Is there more than one binary? As far as I know this "client" spawns a server automatically. There are also those commands:

```
        --start-server    start background server
        --stop-server     stop background server
```

**Comment by maurolacy** [comment]
> Why do you think so?

I've downloaded the binary package, and the `sccache-dist` functionality is different to what is built with `cargo install`.

**Comment by maurolacy** [comment]
Deleting the build artifacts releases more than 1GB of disk space. Closing this; will add that change (removing intermediate stuff) under the #35 issue, along with switching to alpine.

**Comment by webmaster128** [comment]
Good. Then what remains here is a build time issue, which we consider acceptable for now.

> I've downloaded the binary package, and the sccache-dist functionality is different to the sccache that is built with cargo install.

Did you see that for Linux there are two different binaries (`sccache-dist` and `sccache`)?

**Comment by maurolacy** [comment]
> Did you see that for Linux there are two different binaries (`sccache-dist` and `sccache`)?

Not on the package I downloaded... thanks, will take a look at the other ones that are available for Linux.
