### ISSUE TITLE
Avoid the use of rustup

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/rust-optimizer#34]
workspace-optimizer currently [uses rustup to install Rust](https://github.com/CosmWasm/rust-optimizer/blob/v0.10.9/workspace-optimizer.Dockerfile#L11-L14). This is a potential source of friction and in worst case an attack vector as rustup does not error on invalid Rust binary signatures ([_Switch warnings for errors, ensuring that GPG signatures are always checked and valid._](https://github.com/rust-lang/rustup/issues/2028)).

If we find a way around the [unstable --out-dir](https://github.com/rust-lang/cargo/issues/6790) we can use the rust installation of the original docker image.

**Comment by maurolacy** [comment]
By using a shell script (or a shell script wrapper around `optimize_workspace.py`) I think we can easily avoid the use / need of `--out-dir`.

**Comment by webmaster128** [comment]
I'm sure it can be done. It was somewhat hard when I tried last time for various reasons. One is that when calling

```
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/workspace-optimizer:0.10.9
```

you will find *.wasm files from previous builds that are in the `cosmwasm-plus_cache` volume for some reason. You'd need to remove all of them before the build. If I recall correctly, there were other issues I ran into.
