### ISSUE TITLE
Ceate a base image for *-optimizer

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/rust-optimizer#39]
Given that we have two optimizers (`rust-optimizer` and `workspace-optimizer`) and that they share most of their docker setup (i.e. `SHARED` blocks in *.Dockerfile) let's consider creating a `base-optimizer` docker image, to build a base image with the shared part, and then re-use it for both optimizers. This will also ease maintencence / updates, as most of the regular changes (rust version and so) would need to be done in just one place.

Alternatively, let's consider merging both optimizers into one. `workspace-optimizer` functionality could be triggered either by passing a flag (`[-w|--workspace]`, or be automatically detected.

**Comment by maurolacy** [comment]
@webmaster128 what would you prefer / choose, creating a base image, or merging both optimizers? I would go for the merging but, it's your call.

**Comment by webmaster128** [comment]
I'd do one step at a time and start with a base image
