### ISSUE TITLE
ARM build not published

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/rust-optimizer#60]
In 0.12.2 / https://github.com/CosmWasm/rust-optimizer/pull/56 an ARM build of this project was created. This makes the CosmWasm development experience of ARM users much smother as the contract compilation does not need to go through an emulator. However, during our testing it was discovered that this ARM build produces different compilation results than the Intel build. As a consequence the build is not proproducible.

I see a few things to move forward:
1. Ignore reproducible builds (probably bad)
2. Find a way to ensure both images produce the same results
3. Have different image names in order to make explicit on which system a contract is built on

Input welcome. For now, the ARM build is not published to DockerHub.

**Comment by maurolacy** [comment]
This is probably obvious, but I would also list for completeness:

4. Stick to using Intel emulation in ARM machines for reproducibility, and in spite of performance.

**Comment by maurolacy** [comment]
Related to 2.: [Rust issues related to fully reproducible builds](https://github.com/rust-lang/rust/labels/A-reproducibility).

**Comment by maurolacy** [comment]
My impression is that it will be a really long shot to achieve reproducible wasm builds across different processor architectures. In fact, we're currently using docker as an "isolation chamber" to achieve reproducible builds in a _single_ architecture. By fixing things the OS, compiler, installed libs and their versions, etc. We are breaking some (if not all) of those when switching to a different arch.

What about 
5. Publish the ARM build of `rust-optimizer` (let's say, as a tool for aiding testing / development), stating clearly that it does not produce the same builds than the Intel rust-optimizer. And, that for release / production use, contracts built using the Intel one must be used.

Probably a recipe for trouble... perhaps your option 3., adding a suffix to ARM built artifacts, is the best we can do.

**Comment by maurolacy** [comment]
Created #63.
