### ISSUE TITLE
Missing sense of checksums_intermediate.txt

### ISSUE THREAD

**Issue by SteMak** [CosmWasm/rust-optimizer#87]
The `checksums_intermediate.txt` file is generated in the `artifacts` folder with the following data:
```
ARBITRARY_SHA_256_HASH  ./target/wasm32-unknown-unknown/release/CRATE_NAME.wasm
```

However, the `ARBITRARY_SHA_256_HASH` is not hash of the file `./target/wasm32-unknown-unknown/release/CRATE_NAME.wasm`.

I'm really not sure how should I use it, and it is not mentioned in readme what the file is responsible for. Please, let me know why the file is needed, or maybe another hash should be written there.

**Comment by webmaster128** [comment]
You don't need to use it at all. This is a hash of an intermediate result (after compilation, before wasm-opt IIRC). This is indeed not documented, so leaving this open.

**Comment by SteMak** [comment]
Thanks for your answer!
I've discovered, that the file is generated in `optimize.sh` and is used in `optimize_workspace.sh`. I'm not good in docker, but in the `Dockerfile` the files are responsible for different endpoints, so maybe that's why the file is stored there, like between two separate excursions.

But even in such way, I think it is possible to remove the file after all needed actions executed.

**Comment by maurolacy** [comment]
This file is there so that we can check if the results of the **compilation** phase are the same across CPU archs (so far, they are not).
Perhaps it should be better named `checksums_compilation.txt`.

Feel free to ignore / remove this file from your builds.

**Comment by webmaster128** [comment]
Thanks for bringing this up. In the upcoming version 0.15.0 this file is not created anymore. Sorry for the confision.
