### ISSUE TITLE
[workspace-optimizer]: build fails if workspaces inside `contracts/*` hold path dependencies other than `contracts/*` paths

### ISSUE THREAD

**Issue by ever0de** [CosmWasm/rust-optimizer#88]
If internal crates exist other than `contracts/*`, it seems that workspace-optimizer doesn't build with wasm target. 
It appears to be building with no_std, not wasm.

ex path tree)
```
├── contracts
│   └── counter-contract
├── crates
│   ├── msg
```
Here workspace-optimizer will fail if counter-contract is holding msg as path dependency.

Does anyone know anything about this?

**Comment by webmaster128** [comment]
workspace-optimizer only looks for workspace members in the `contracts/` folder. If you want a contract to be built, it needs to be moved there. However, other dependencies can be in other folders. In https://github.com/CosmWasm/cw-plus there are contracts under `contracts/` and helper packages under `packages/`. Those packages are built as part of the contract build process. They don't have their own Wasm output.

**Comment by ever0de** [comment]
> workspace-optimizer only looks for workspace members in the `contracts/` folder. If you want a contract to be built, it needs to be moved there. However, other dependencies can be in other folders. In https://github.com/CosmWasm/cw-plus there are contracts under `contracts/` and helper packages under `packages/`. Those packages are built as part of the contract build process. They don't have their own Wasm output.

I will check the `cw-plus` repository. Thank you.

**Comment by ever0de** [comment]
@webmaster128 
Should external dependencies (those in packages/* in cw-plus) be deployed to registry(crates.io)?

**Comment by webmaster128** [comment]
`packages/storage-plus` is publiched to crates.io for sure. I don't know about the other ones.

But if they are just internal packages used in your repository, you don't need to publich them.

**Comment by ever0de** [comment]
Hmm... I don't know what cw-plus is different from my current situation.

**Comment by webmaster128** [comment]
What's your issue/error then?

**Comment by ever0de** [comment]
The situation seems the same, but I can't build.

**Comment by webmaster128** [comment]
What is "can't build"? What did you do exactly? What error do you get exactly?

**Comment by ever0de** [comment]
In general, it seems that the allocator is not set, and I will create a repository that can reproduce this.

```
error[E0463]: can't find crate for `std`
// ...
   = note: the `wasm32-unknown-unknown` target may not be installed
   = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
```

**Comment by ever0de** [comment]
<https://github.com/ever0de/cw-workspace-optimizer-report>

Environment
- macOS Monterey 12.5
- rust version: 1.62.0 (specified in toolchain)

Command used
```
docker run --rm -v "$(pwd)":/code \
   --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
   --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
   cosmwasm/workspace-optimizer:0.12.6
```

Failed to load from std module

**Comment by ever0de** [comment]
First of all, if I were to do a self-report, I should have included the content more clearly in the first part. sorry.

If the rust-toolchain file does not exist, it works normally.
- It was confirmed that the problem was using the toolchain file, not the problem of a specific version.

Is it difficult to support toolchain files?
I don't want the Rust version of my project to change suddenly and incur overhead costs.

**Comment by webmaster128** [comment]
The whole point of rust-optimizer and workspace-optimizer is to be able to create **reproducible** production builds. For every Rust version the output changes. For this reason, every optimizer version comes with a specific version of Rust thatr is clearly documented in the CHANGELOG of this repo. The Rust-optimizer should not download a different compiler version at runtime for simplicity.

>  I don't want the Rust version of my project to change suddenly and incur overhead costs.

I would not recommend that strictness. All you need to do is specify a minimal version for the project. If someone builds with a more recent version, cool. If someone builds with a version that is too old, they will get compile errors. In general it is nice of the source code compiles with a reasonably wide range of compilers. E.g. you can say you require >= 1.59, workspace-optimizer uses 1.60, your CI uses 1.62 and another developer might use latest stable 1.63. There is nothing wrong with that.

**Comment by ever0de** [comment]
I agree with your opinion.
The slightly different thing is to prevent CI from failing indiscriminately (although it's actually regular) by linter rules like clippy.

Thank you very much for your reply.
I don't think there will be any further problems after that, can I close the issue?

**Comment by webmaster128** [comment]
> The slightly different thing is to prevent CI from failing indiscriminately (although it's actually regular) by linter rules like clippy.

In CosmWasm we do this:
- Run all CI jobs with the minimal supported version
- Have a dedicated [clippy job that is run on both the min version as well as the latest stable](https://github.com/CosmWasm/cosmwasm/blob/af3ed179b2a8f7807c7eccb9e23fb110b213c248/.circleci/config.yml#L30-L34). When updating the latest stable, we [fix the clippy issues in the same PR](https://github.com/CosmWasm/cosmwasm/pull/1383).

I think what is left here is that the optimizer should have a better error message in case a `rust-toolchain` file is found.
