### ISSUE TITLE
Docker "latest" tag is not found

### ISSUE THREAD

**Issue by SteMak** [CosmWasm/rust-optimizer#90]
### Overview
Docker tag `latest` is useful as it is possible for scripts using the docker image to be always up-to-date.

### Problem
No `latest` tag found:
```
docker: Error response from daemon: manifest for \
cosmwasm/rust-optimizer:latest not found: manifest unknown: manifest unknown.
```

### Note
If it may happen that `latest` tag may be unstable, provide additional `stable` tag for marking container version tested by time.

**Comment by webmaster128** [comment]
What's the use case for that? The builder version should be fixed. Otherwise your builds are not reproducible.

**Comment by SteMak** [comment]
The main use case is developing.
Of course, for production all unstable versions should be locked, but for developing it is better to upgrade dependencies automatically to use the `latest` version with the newest features.

One more point: template projects, documentation, etc. should not be modified any time new version is released.
Example: [CosmWasm Docs](https://docs.cosmwasm.com/docs/0.14/getting-started/compile-contract#optimized-compilation) contains outdated `rust-optimizer` version and may be easy fixed by using `latest` tag.

**Comment by webmaster128** [comment]
I see your point. However, we should discourage any sort of usage of this project without version pinning as this created builds that are not reproducible. We should clarify this as part of #101.
