### ISSUE TITLE
Updating the `wasm-opt` tool

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/rust-optimizer#96]
The newest version of the `wasm-opt` tool was released ten months ago so it is sometimes already. Apparently, it allows saving 25% of the binary size in some cases. We should consider migrating to it especially considering existing problems like: https://github.com/CosmWasm/wasmd/issues/1038.

**Comment by webmaster128** [comment]
Where do you get this 25% from? I'm running the latest wasm-opt version 110 together with Rust 1.64.0 locally and don't see size differences to rust-opimizer 0.12.9 across 3 different contracts.

But sure, it can be updated 👍 Does not hurt either way.

**Comment by gmanev7** [comment]
I have had a similar experience with a contract. We use extensively static code dispatching and with the current binaryen version 105 we observe binary sizes to correlate to the number of trait implementors.

**Comment by webmaster128** [comment]
Published as part of 0.12.10
